// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axeryakwzlyqecoijwfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4ZXJ5YWt3emx5cWVjb2lqd2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTcxOTMsImV4cCI6MjA2NjMzMzE5M30.m8wNYCsEYhIUjFk3qQ8V3wRfdtCXU_Xm1RJe8p8K4E8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);